'use strict';

// ─── BLENDER BOT MODEL PACK 46 ──────────────────────────────────────────────
// Runtime geometry is generated by Blender from the canonical modular .blend/.glb.
// This keeps file:// support without image planes, textures or network fetches.

const BOT_MODEL_46_COMPONENTS=Object.freeze({
  head:'ZAP_Head',torso:'ZAP_Torso',pelvis:'ZAP_Pelvis',shoulder:'ZAP_Shoulder',
  upperArm:'ZAP_UpperArm',forearm:'ZAP_Forearm',hand:'ZAP_Hand',
  thigh:'ZAP_Thigh',shin:'ZAP_Shin',foot:'ZAP_Foot'
});
const BOT_MODEL_46_ROLE_COMPONENTS=Object.freeze({
  assault:'ZAP_Role_Assault',
  sniper:'ZAP_Role_Sniper',
  engineer:'ZAP_Role_Engineer',
  anchor:'ZAP_Role_Anchor',
  flanker:'ZAP_Role_Flanker'
});
const _BOT_MODEL_46_GEOMETRIES=new Map();
const _BOT_MODEL_46_MATERIALS=new Map();

function botModel46Available(){
  const pack=window.ZAP_BOT_MODEL_46;
  if(!pack||pack.version!==46||!pack.components)return false;
  return [...Object.values(BOT_MODEL_46_COMPONENTS),...Object.values(BOT_MODEL_46_ROLE_COMPONENTS)]
    .every(name=>pack.components[name]);
}
function botModel46Materials(team){
  const key=team==='ally'?'ally':'enemy';
  if(_BOT_MODEL_46_MATERIALS.has(key))return _BOT_MODEL_46_MATERIALS.get(key);
  const ally=key==='ally';
  // Arena lighting has no scene.environment/HDR reflection source, so highly
  // metallic shell values lose too much diffuse response at gameplay distance.
  // Use moderate metalness plus a subtle team tint on neutral hardware, while
  // reserving saturated paint for the large MAT_ACCENT identification panels.
  const accent=ally?0x2f97ff:0xef4052;
  const shell=ally?0x506476:0x62565b;
  const edge=ally?0x8295a7:0x8b7d82;
  const glow=ally?0x6ef1ff:0xff5360;
  const accentGlowIntensity=ally?.22:.17;
  const glowIntensity=ally?1.65:1.12;
  // Keep the large visor saturated glass, not a blown-out white/salmon panel.
  // Small MAT_GLOW accents stay brighter; the visor carries team identity by hue.
  const visorGlowIntensity=ally?1.30:.84;
  const VisorMaterial=THREE.MeshPhysicalMaterial||THREE.MeshStandardMaterial;
  const set=Object.freeze({
    MAT_DARK:new THREE.MeshStandardMaterial({color:0x0a1017,roughness:.60,metalness:.14}),
    MAT_SHELL:new THREE.MeshStandardMaterial({color:shell,roughness:.34,metalness:.36}),
    MAT_EDGE:new THREE.MeshStandardMaterial({color:edge,roughness:.30,metalness:.48}),
    MAT_ACCENT:new THREE.MeshStandardMaterial({color:accent,roughness:.34,metalness:.10,emissive:accent,emissiveIntensity:accentGlowIntensity}),
    MAT_GLOW:new THREE.MeshStandardMaterial({color:glow,roughness:.16,metalness:.08,emissive:glow,emissiveIntensity:glowIntensity}),
    MAT_VISOR:new VisorMaterial({color:ally?0x074957:0x4a1018,roughness:.12,metalness:.10,clearcoat:1,clearcoatRoughness:.08,emissive:glow,emissiveIntensity:visorGlowIntensity}),
    MAT_RUBBER:new THREE.MeshStandardMaterial({color:0x040609,roughness:.84,metalness:.03})
  });
  _BOT_MODEL_46_MATERIALS.set(key,set);
  return set;
}
function decodeBot46Q16(encoded){
  const raw=atob(encoded||'');
  if(!raw)return new Float32Array(0);
  const bytes=new Uint8Array(raw.length);
  for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);
  const src=new Int16Array(bytes.buffer);
  const out=new Float32Array(src.length);
  for(let i=0;i<src.length;i++)out[i]=src[i]/32767;
  return out;
}
function botModel46Geometry(componentName){
  if(_BOT_MODEL_46_GEOMETRIES.has(componentName))return _BOT_MODEL_46_GEOMETRIES.get(componentName);
  const data=window.ZAP_BOT_MODEL_46?.components?.[componentName];
  if(!data)return null;
  const positions=data.p||decodeBot46Q16(data.p16);
  const normals=data.n||decodeBot46Q16(data.n16);
  if(!positions.length||positions.length!==normals.length)return null;
  const geo=new THREE.BufferGeometry();
  geo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));
  geo.setAttribute('normal',new THREE.Float32BufferAttribute(normals,3));
  geo.clearGroups();
  const materialNames=[];
  for(const group of data.groups||[]){
    let idx=materialNames.indexOf(group.material);
    if(idx<0){idx=materialNames.length;materialNames.push(group.material);}
    geo.addGroup(group.start,group.count,idx);
  }
  geo.computeBoundingBox();geo.computeBoundingSphere();
  geo.userData.botMaterialNames=materialNames;
  _BOT_MODEL_46_GEOMETRIES.set(componentName,geo);
  return geo;
}
function createBotModel46Component(componentName,team){
  const geo=botModel46Geometry(componentName);if(!geo)return null;
  const set=botModel46Materials(team);
  const mats=(geo.userData.botMaterialNames||[]).map(name=>set[name]||set.MAT_DARK);
  const mesh=new THREE.Mesh(geo,mats);
  mesh.name='bot46-'+componentName;
  mesh.castShadow=!MOBILE_LOW;
  mesh.receiveShadow=false;
  return mesh;
}
function hideBot46LegacySurface(mesh){
  const mat=mesh?.material;
  if(Array.isArray(mat)){
    for(const m of mat)if(m)m.visible=false;
  }else if(mat){
    mat.visible=false;
  }
}
function botModel46NeedsLowPowerFallback(){
  if(!MOBILE_LOW)return false;
  const touchPoints=typeof navigator==='object'?Number(navigator.maxTouchPoints)||0:0;
  const coarsePointer=typeof matchMedia==='function'&&matchMedia('(pointer: coarse)').matches;
  return touchPoints>0&&coarsePointer;
}
function botModel46RoleVariant(role,weaponKey=''){
  if(weaponKey==='sniper')return'sniper';
  if(role==='engineer')return'engineer';
  if(role==='anchor')return'anchor';
  if(role==='flankL'||role==='flankR')return'flanker';
  return'assault';
}
function syncBotModel46RoleVariant(bot){
  const model=bot?.model46;
  if(!model?.roleModules)return false;
  const next=botModel46RoleVariant(bot.role,bot.weapon?.key);
  if(model.roleVariant===next)return true;
  for(const [key,module] of Object.entries(model.roleModules))module.visible=key===next;
  model.roleVariant=next;
  return true;
}
function installBotModel46Rig({team,pts,legRig,leftHand,rightHand,proceduralDecor}){
  if(botModel46NeedsLowPowerFallback()||!botModel46Available()||!pts||!legRig||!leftHand||!rightHand)return null;
  for(const m of pts)hideBot46LegacySurface(m);
  hideBot46LegacySurface(leftHand);hideBot46LegacySurface(rightHand);
  for(const obj of proceduralDecor||[])obj.visible=false;

  const add=(parent,key,pos=null,mirror=1,scale=[1,1,1],inheritParentFacing=false)=>{
    const mesh=createBotModel46Component(BOT_MODEL_46_COMPONENTS[key],team);
    if(!mesh)return null;
    if(pos)mesh.position.set(...pos);
    // Pack46 is authored facing Blender +Y, which the runtime derivative maps
    // to local -Z. Bot gameplay yaw/muzzle semantics use local +Z as forward.
    // Rotate presentation-only components here instead of corrupting gameplay
    // hit meshes, AI yaw or projectile math. Hands inherit the corrected
    // weapon-pivot quaternion, so they must not receive this offset twice.
    if(!inheritParentFacing)mesh.rotation.y=Math.PI;
    mesh.scale.set(scale[0]*mirror,scale[1],scale[2]);
    parent.add(mesh);return mesh;
  };
  const visual={
    head:add(pts[1],'head',[0,-.125,0],1,[.92,.95,.92]),
    torso:add(pts[2],'torso',null,1,[1.16,1.05,1.10]),
    pelvis:add(pts[3],'pelvis',null,1,[1.12,1.04,1.08]),
    leftUpper:add(pts[4],'upperArm',null,-1,[1.12,1.05,1.10]),
    rightUpper:add(pts[5],'upperArm',null,1,[1.12,1.05,1.10]),
    leftShoulder:add(pts[4],'shoulder',[0,-.235,0],-1,[1.18,1.10,1.12]),
    rightShoulder:add(pts[5],'shoulder',[0,-.235,0],1,[1.18,1.10,1.12]),
    leftFore:add(pts[6],'forearm',null,-1,[1.15,1.05,1.10]),
    rightFore:add(pts[7],'forearm',null,1,[1.15,1.05,1.10]),
    leftHand:add(leftHand,'hand',null,-1,[1.04,1.03,1.04],true),
    rightHand:add(rightHand,'hand',null,1,[1.04,1.03,1.04],true),
    leftThigh:add(legRig.left.hip,'thigh',[0,-.235,0],-1,[1.16,1.06,1.12]),
    rightThigh:add(legRig.right.hip,'thigh',[0,-.235,0],1,[1.16,1.06,1.12]),
    leftShin:add(legRig.left.knee,'shin',[0,-.195,0],-1,[1.13,1.05,1.10]),
    rightShin:add(legRig.right.knee,'shin',[0,-.195,0],1,[1.13,1.05,1.10]),
    leftFoot:add(legRig.left.ankle,'foot',[0,.035,0],-1,[1.15,1.05,1.14]),
    rightFoot:add(legRig.right.ankle,'foot',[0,.035,0],1,[1.15,1.05,1.14])
  };
  if(Object.values(visual).some(v=>!v))return null;

  // Role modules are Blender geometry parented to the visual torso, so they
  // inherit torso motion but never enter pts[] or any gameplay collision owner.
  const roleModules={};
  for(const [variant,componentName] of Object.entries(BOT_MODEL_46_ROLE_COMPONENTS)){
    const mesh=createBotModel46Component(componentName,team);
    if(!mesh)return null;
    mesh.visible=false;
    visual.torso.add(mesh);
    roleModules[variant]=mesh;
  }
  visual.roleModules=roleModules;
  visual.roleVariant=null;
  return visual;
}
