import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,statSync} from 'node:fs';
import {createHash} from 'node:crypto';
import vm from 'node:vm';

class Attr{constructor(array,itemSize){this.array=array;this.itemSize=itemSize;}}
class Geometry{
  constructor(){this.attributes={};this.groups=[];this.userData={};}
  setAttribute(name,value){this.attributes[name]=value;return this;}
  clearGroups(){this.groups=[];}
  addGroup(start,count,materialIndex){this.groups.push({start,count,materialIndex});}
  computeBoundingBox(){}
  computeBoundingSphere(){}
}
class Material{
  constructor(opts={}){Object.assign(this,opts);this.visible=true;}
}
class Node{
  constructor(){
    this.children=[];
    this.position={x:0,y:0,z:0,set(x,y,z){this.x=x;this.y=y;this.z=z;}};
    this.rotation={x:0,y:0,z:0,set(x,y,z){this.x=x;this.y=y;this.z=z;}};
    this.scale={x:1,y:1,z:1,set(x,y,z){this.x=x;this.y=y;this.z=z;}};
  }
  add(child){this.children.push(child);child.parent=this;}
}
class Mesh extends Node{
  constructor(geometry=null,material=null){super();this.geometry=geometry;this.material=material;this.castShadow=false;this.receiveShadow=false;this.name='';}
}
const names=[
  'ZAP_Head','ZAP_Torso','ZAP_Pelvis','ZAP_Shoulder','ZAP_UpperArm','ZAP_Forearm','ZAP_Hand','ZAP_Thigh','ZAP_Shin','ZAP_Foot',
  'ZAP_Role_Assault','ZAP_Role_Sniper','ZAP_Role_Engineer','ZAP_Role_Anchor','ZAP_Role_Flanker'
];
const components=Object.fromEntries(names.map(name=>[name,{
  p:[0,0,0,1,0,0,0,1,0],
  n:[0,0,1,0,0,1,0,0,1],
  groups:[{start:0,count:3,material:name==='ZAP_Shoulder'?'MAT_ACCENT':'MAT_SHELL'}]
}]));
const context={
  MOBILE_LOW:false,
  navigator:{maxTouchPoints:0},
  matchMedia:()=>({matches:false}),
  atob:value=>Buffer.from(value,'base64').toString('binary'),
  THREE:{BufferGeometry:Geometry,Float32BufferAttribute:Attr,MeshStandardMaterial:Material,Mesh},
  ZAP_BOT_MODEL_46:{version:46,components}
};
context.window=context;
vm.createContext(context);
const source=readFileSync(new URL('../src/entities/bot-model3d.js',import.meta.url),'utf8');
vm.runInContext(source+'\n;globalThis.__BOT46_TEST__={botModel46Available,botModel46Materials,botModel46NeedsLowPowerFallback,botModel46RoleVariant,syncBotModel46RoleVariant,decodeBot46Q16,botModel46Geometry,createBotModel46Component,installBotModel46Rig};',context,{filename:'src/entities/bot-model3d.js'});
const api=context.__BOT46_TEST__;
const manifestUrl=new URL('../asset-staging/2026-10-06-bot-3d-pack-46/manifest.json',import.meta.url);
const manifest=JSON.parse(readFileSync(manifestUrl,'utf8'));
function fileIdentity(url){
  const bytes=readFileSync(url);
  return {bytes:statSync(url).size,sha256:createHash('sha256').update(bytes).digest('hex')};
}

function node(){const n=new Node();n.material=new Material();return n;}
function makeLeg(){return{hip:node(),knee:node(),ankle:node()};}

test('Pack46 generated manifest matches artifacts and q16 geometry contract',()=>{
  assert.equal(manifest.schema,1);
  assert.equal(manifest.packVersion,46);
  assert.equal(manifest.blenderVersion,'5.2.2 LTS');
  assert.deepEqual(Object.keys(manifest.components),names);
  for(const [name,stats] of Object.entries(manifest.components)){
    assert.ok(stats.triangles>0,`${name} must contain triangles`);
    assert.equal(stats.runtimeVertices,stats.triangles*3,`${name} runtime derivative must be non-indexed triangles`);
    assert.ok(stats.materialGroups>=1,`${name} must retain material groups`);
    assert.ok(stats.maxAbsLocalCoordinate<=1,`${name} must fit the q16 local coordinate range`);
  }
  const artifacts={
    glb:new URL('../assets/characters/models/zap-bot-modular-46.glb',import.meta.url),
    runtimeJs:new URL('../assets/characters/models/zap-bot-modular-46.runtime.js',import.meta.url),
    blend:new URL('../asset-staging/2026-10-06-bot-3d-pack-46/zap-bot-modular-46.blend',import.meta.url),
    preview:new URL('../asset-staging/2026-10-06-bot-3d-pack-46/zap-bot-modular-preview-46.png',import.meta.url),
    builder:new URL('../asset-staging/2026-10-06-bot-3d-pack-46/build_bot_3d.py',import.meta.url)
  };
  for(const [key,url] of Object.entries(artifacts))assert.deepEqual(fileIdentity(url),manifest.artifacts[key],`${key} must be regenerated by the canonical Blender builder`);
});

test('Pack46 availability requires the complete Blender component contract',()=>{
  assert.equal(api.botModel46Available(),true);
  const foot=context.ZAP_BOT_MODEL_46.components.ZAP_Foot;
  delete context.ZAP_BOT_MODEL_46.components.ZAP_Foot;
  assert.equal(api.botModel46Available(),false);
  context.ZAP_BOT_MODEL_46.components.ZAP_Foot=foot;
});

test('Pack46 q16 decoder preserves normalized geometry values',()=>{
  const raw=Int16Array.from([0,16384,-16384,32767,-32767]);
  const encoded=Buffer.from(raw.buffer).toString('base64');
  const decoded=api.decodeBot46Q16(encoded);
  assert.equal(decoded.length,raw.length);
  assert.ok(Math.abs(decoded[0])<1e-7);
  assert.ok(Math.abs(decoded[1]-.5000153)<1e-5);
  assert.ok(Math.abs(decoded[2]+.5000153)<1e-5);
  assert.equal(decoded[3],1);
  assert.equal(decoded[4],-1);
});

test('Pack46 builds shared Three.js geometry with material groups',()=>{
  const a=api.createBotModel46Component('ZAP_Shoulder','ally');
  const b=api.createBotModel46Component('ZAP_Shoulder','enemy');
  assert.ok(a instanceof Mesh&&b instanceof Mesh);
  assert.equal(a.geometry,b.geometry,'geometry must be shared across teams');
  assert.equal(a.geometry.attributes.position.array.length,9);
  assert.equal(a.geometry.groups.length,1);
  const allyAccent=api.createBotModel46Component('ZAP_Shoulder','ally').material[0].color;
  const enemyAccent=api.createBotModel46Component('ZAP_Shoulder','enemy').material[0].color;
  assert.notEqual(allyAccent,enemyAccent,'team accent materials must differ');
});

test('Pack46 high-visibility team palette stays saturated without flattening the PBR hierarchy',()=>{
  const ally=api.botModel46Materials('ally');
  const enemy=api.botModel46Materials('enemy');
  assert.equal(ally.MAT_SHELL.color,0x506476);
  assert.equal(enemy.MAT_SHELL.color,0x62565b);
  assert.equal(ally.MAT_EDGE.color,0x8295a7);
  assert.equal(enemy.MAT_EDGE.color,0x8b7d82);
  assert.equal(ally.MAT_SHELL.metalness,.36);
  assert.equal(enemy.MAT_SHELL.metalness,.36);
  assert.equal(ally.MAT_EDGE.metalness,.48);
  assert.equal(enemy.MAT_EDGE.metalness,.48);
  assert.equal(ally.MAT_ACCENT.color,0x2f97ff);
  assert.equal(enemy.MAT_ACCENT.color,0xef4052);
  assert.equal(ally.MAT_ACCENT.emissiveIntensity,.22);
  assert.equal(enemy.MAT_ACCENT.emissiveIntensity,.17);
  assert.equal(ally.MAT_ACCENT.metalness,.10);
  assert.equal(enemy.MAT_ACCENT.metalness,.10);
  assert.equal(ally.MAT_VISOR.color,0x074957);
  assert.equal(enemy.MAT_VISOR.color,0x4a1018);
  assert.equal(ally.MAT_VISOR.emissiveIntensity,1.30);
  assert.equal(enemy.MAT_VISOR.emissiveIntensity,.84);
  assert.ok(ally.MAT_ACCENT.emissiveIntensity<ally.MAT_VISOR.emissiveIntensity,'ally armor accent must remain a shaded surface, not flat neon');
  assert.ok(enemy.MAT_ACCENT.emissiveIntensity<enemy.MAT_VISOR.emissiveIntensity,'enemy armor accent must remain a shaded surface, not flat neon');
  assert.ok(ally.MAT_VISOR.emissiveIntensity<ally.MAT_GLOW.emissiveIntensity,'ally visor must not outshine small cyan accents');
  assert.ok(enemy.MAT_VISOR.emissiveIntensity<enemy.MAT_GLOW.emissiveIntensity,'enemy visor must not blow out into salmon/pink');
});

test('Pack46 remains enabled for a desktop even when global PERF/MOBILE_LOW is active',()=>{
  context.MOBILE_LOW=true;
  context.navigator.maxTouchPoints=0;
  context.matchMedia=()=>({matches:false});
  assert.equal(api.botModel46NeedsLowPowerFallback(),false);
  const pts=Array.from({length:14},()=>node());
  const visual=api.installBotModel46Rig({
    team:'ally',
    pts,
    legRig:{root:node(),left:makeLeg(),right:makeLeg()},
    leftHand:node(),
    rightHand:node(),
    proceduralDecor:[]
  });
  assert.ok(visual,'desktop low-perf mode must keep the Blender model');
  assert.equal(Object.keys(visual).length,19);
  assert.equal(Object.keys(visual.roleModules).length,5);
  context.MOBILE_LOW=false;
});

test('Pack46 keeps the lightweight fallback for low-power coarse touch devices',()=>{
  context.MOBILE_LOW=true;
  context.navigator.maxTouchPoints=5;
  context.matchMedia=query=>({matches:query==='(pointer: coarse)'});
  assert.equal(api.botModel46NeedsLowPowerFallback(),true);
  const visual=api.installBotModel46Rig({
    team:'enemy',
    pts:Array.from({length:14},()=>node()),
    legRig:{root:node(),left:makeLeg(),right:makeLeg()},
    leftHand:node(),
    rightHand:node(),
    proceduralDecor:[]
  });
  assert.equal(visual,null);
  context.MOBILE_LOW=false;
  context.navigator.maxTouchPoints=0;
  context.matchMedia=()=>({matches:false});
});

test('Pack46 installs volume parts over hidden legacy surfaces without replacing gameplay nodes',()=>{
  const pts=Array.from({length:14},()=>node());
  const leftHand=node(),rightHand=node();
  const legRig={root:node(),left:makeLeg(),right:makeLeg()};
  const legacy=[{visible:true},{visible:true}];
  const visual=api.installBotModel46Rig({team:'enemy',pts,legRig,leftHand,rightHand,proceduralDecor:legacy});
  assert.ok(visual);
  assert.equal(Object.keys(visual).length,19);
  assert.equal(Object.keys(visual.roleModules).length,5);
  assert.ok(pts.every(p=>p.material.visible===false),'gameplay hit meshes remain but their surfaces are hidden: '+pts.map(p=>p.material.visible).join(','));
  assert.equal(leftHand.material.visible,false);
  assert.equal(rightHand.material.visible,false);
  assert.ok(legacy.every(x=>x.visible===false));
  assert.ok(pts[1].children.some(x=>x.name==='bot46-ZAP_Head'));
  assert.ok(pts[2].children.some(x=>x.name==='bot46-ZAP_Torso'));
  assert.ok(legRig.left.hip.children.some(x=>x.name==='bot46-ZAP_Thigh'));
  assert.ok(legRig.right.ankle.children.some(x=>x.name==='bot46-ZAP_Foot'));
  assert.equal(visual.head.rotation.y,Math.PI,'Pack46 head must face gameplay +Z instead of authored -Z');
  assert.equal(visual.torso.rotation.y,Math.PI,'Pack46 torso must share the gameplay-facing convention');
  assert.equal(visual.leftThigh.rotation.y,Math.PI,'Pack46 leg armor must not remain backwards');
  assert.equal(visual.leftHand.rotation.y,0,'weapon-driven hand already inherits the corrected pivot yaw and must not double-rotate');
});


test('Pack46 maps live AI roles and sniper weapons onto one visible Blender role module',()=>{
  const pts=Array.from({length:14},()=>node());
  const visual=api.installBotModel46Rig({
    team:'ally',pts,legRig:{root:node(),left:makeLeg(),right:makeLeg()},
    leftHand:node(),rightHand:node(),proceduralDecor:[]
  });
  const bot={model46:visual,role:'flankL',weapon:{key:'plasma'}};
  assert.equal(api.syncBotModel46RoleVariant(bot),true);
  assert.equal(visual.roleVariant,'flanker');
  assert.equal(visual.roleModules.flanker.visible,true);
  assert.equal(Object.values(visual.roleModules).filter(x=>x.visible).length,1);
  bot.role='anchor';bot.weapon={key:'sniper'};
  api.syncBotModel46RoleVariant(bot);
  assert.equal(visual.roleVariant,'sniper','sniper weapon appearance overrides the broader anchor chassis role');
  assert.equal(visual.roleModules.sniper.visible,true);
  assert.equal(Object.values(visual.roleModules).filter(x=>x.visible).length,1);
  assert.equal(api.botModel46RoleVariant('engineer','plasma'),'engineer');
  assert.equal(api.botModel46RoleVariant('assault','rifle'),'assault');
});
