import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const source=readFileSync(new URL('../src/combat/projectile-ricochet.js',import.meta.url),'utf8');
function createHarness(){const context={};vm.createContext(context);vm.runInContext(source+'\n;globalThis.__R={PROJECTILE_RICOCHET_MAX,projectileRicochetPolicy,rollProjectileRicochet,reflectProjectileDirection};',context,{filename:'src/combat/projectile-ricochet.js'});return context.__R;}
class Vec3{constructor(x=0,y=0,z=0){this.x=x;this.y=y;this.z=z;}copy(v){this.x=v.x;this.y=v.y;this.z=v.z;return this;}dot(v){return this.x*v.x+this.y*v.y+this.z*v.z;}reflect(n){const s=2*this.dot(n);this.x-=s*n.x;this.y-=s*n.y;this.z-=s*n.z;return this;}length(){return Math.hypot(this.x,this.y,this.z);}normalize(){const l=this.length()||1;this.x/=l;this.y/=l;this.z/=l;return this;}}
function near(a,e,l,eps=1e-12){assert.ok(Math.abs(a-e)<=eps,l+' expected '+e+', got '+a);}
test('player and enemy material likelihoods stay explicit while bounce energy is shared',()=>{const {PROJECTILE_RICOCHET_MAX,projectileRicochetPolicy}=createHarness();assert.equal(PROJECTILE_RICOCHET_MAX,1);const expected={player:{metal:[.48,.82],concrete:[.30,.42],wood:[.16,.08]},enemy:{metal:[.46,.76],concrete:[.27,.30],wood:[.12,.04]}};for(const [o,p] of [['player',true],['enemy',false]])for(const m of ['metal','concrete','wood']){const q=projectileRicochetPolicy(m,p);near(q.limit,expected[o][m][0],o+' '+m+' limit');near(q.chance,expected[o][m][1],o+' '+m+' chance');assert.ok(q.speedRetention>0&&q.speedRetention<=1);assert.ok(q.damageRetention>0&&q.damageRetention<=1);assert.equal(q.maxRicochets,1);near(q.offset,.09,m+' offset');}assert.equal(projectileRicochetPolicy('unknown',true).material,'concrete');});
test('shallow incidence can ricochet and exact/steeper limits cannot',()=>{const {rollProjectileRicochet,projectileRicochetPolicy}=createHarness();for(const m of ['metal','concrete','wood']){const p=projectileRicochetPolicy(m,true);assert.ok(rollProjectileRicochet(m,p.limit-1e-6,0,true,()=>0));assert.equal(rollProjectileRicochet(m,p.limit,0,true,()=>0),null);assert.equal(rollProjectileRicochet(m,p.limit+.01,0,true,()=>0),null);}});
test('chance comparison preserves strict less-than semantics',()=>{const {rollProjectileRicochet,projectileRicochetPolicy}=createHarness();for(const p of [true,false]){const q=projectileRicochetPolicy('metal',p);assert.ok(rollProjectileRicochet('metal',.01,0,p,()=>q.chance-1e-9));assert.equal(rollProjectileRicochet('metal',.01,0,p,()=>q.chance),null);}});
test('ineligible impacts and one-ricochet cap consume no RNG',()=>{const {rollProjectileRicochet}=createHarness();let calls=0;const rnd=()=>{calls++;return 0;};assert.equal(rollProjectileRicochet('metal',.9,0,true,rnd),null);assert.equal(rollProjectileRicochet('metal',.01,1,true,rnd),null);assert.equal(calls,0);assert.ok(rollProjectileRicochet('metal',.01,0,true,rnd));assert.equal(calls,1);});
test('reflection flips only the normal component and returns a unit direction',()=>{const {reflectProjectileDirection}=createHarness();const incoming=new Vec3(1,-.25,.5).normalize(),out=new Vec3();const r=reflectProjectileDirection(incoming,new Vec3(0,1,0),out);assert.equal(r,out);near(r.x,incoming.x,'x');near(r.z,incoming.z,'z');near(r.y,-incoming.y,'y');near(r.length(),1,'length');});
